## El objetivo de este proyecto es efectuar un Análisis Explotario de Datos y algunos pasos previos de limpieza tales como:  
# 1.- Eliminar rellenar nulos con la media de la columna, 
# 2.- Contar total de registros faltantes por fecha

AQUI VAMOS A CARGAR EL ARCHIVO QUE NOS MANDO EL PROFESOR

In [1]:
#En esta parte nos dedicamos a cargar el archivo usando la libreria de Pandas.
import pandas as pd
#Descubrimos que la funcion pd.read_csv tambien sirve para leer datos txt de manera eficiente. En este caso, desde mi computador pongo el
#path completo de donde tengo guardado mi proyecto.
df = pd.read_csv("C:\\CienciaDeDatos\\Modulo 2 - Pandas\\Datasets\\25001.txt", encoding='ISO-8859-1', sep ="\s+",na_values="Nulo",skiprows= 18)

<>:5: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<>:5: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
C:\Users\tocha\AppData\Local\Temp\ipykernel_26104\3824888344.py:5: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
  df = pd.read_csv("C:\\CienciaDeDatos\\Modulo 2 - Pandas\\Datasets\\25001.txt", encoding='ISO-8859-1', sep ="\s+",na_values="Nulo",skiprows= 18)

In [2]:
df.head()

        FECHA  (MM)  (MM).1  (°C)  (°C).1
0  01/01/1961   0.0     NaN  25.0    13.0
1  02/01/1961   0.0     NaN  27.5    14.0
2  03/01/1961   0.0     NaN  31.0    11.0
3  04/01/1961   0.0     NaN  32.0    13.0
4  05/01/1961   0.0     NaN  29.0    14.0

In [4]:
df.shape

(19575, 5)

In [5]:
df.dtypes

FECHA         str
(MM)      float64
(MM).1    float64
(°C)      float64
(°C).1    float64
dtype: object

In [6]:
df.axes

[RangeIndex(start=0, stop=19575, step=1),
 Index(['FECHA', '(MM)', '(MM).1', '(°C)', '(°C).1'], dtype='str')]

In [2]:
#En esta parte cambiamos el nombre de las columnas para tener congruencia en la limpieza de los datos y saber que se esta quitando, ademas de 
#ordenar el dataframe base a la fecha.
df.rename(mapper={"(MM)":"PRECIP","(MM).1": "EVAP", "(°C)": "TMAX", "(°C).1": "TIMN"},axis=1, inplace = True)

In [3]:
#Durante esta parte, eliminamos la celda 19574 ya que no proporciona ningun uso (es una serie de lineas divisoras del cuadro ---------)
df.tail()
df = df.drop(19574)

In [4]:
#Como se analizo en gracias al metodo de dtypes, FECHA queda como str, sin embargo no nos sirve para hacer analisis dentro de la variable
#para ello lo convertimos en un datetime.
df['FECHA'] = pd.to_datetime(df['FECHA'], dayfirst= True)

#En este momento nos arrojaba un error porque leia las lineas ------  de la ultima fila, para eliminarlas se hizo lo siguiente
#df = df.drop(19574) 
df.dtypes

FECHA     datetime64[us]
PRECIP           float64
EVAP             float64
TMAX             float64
TIMN             float64
dtype: object

In [10]:
df.head()

       FECHA  PRECIP  EVAP  TMAX  TIMN
0 1961-01-01     0.0   NaN  25.0  13.0
1 1961-01-02     0.0   NaN  27.5  14.0
2 1961-01-03     0.0   NaN  31.0  11.0
3 1961-01-04     0.0   NaN  32.0  13.0
4 1961-01-05     0.0   NaN  29.0  14.0

In [5]:
#Conocemos aqui la media de cada columna para luego revisar si concuerda con los campos rellenados
print(df.describe())
#De esta manera conozco si hay nulos en cada una de las columnas, para saber si puedo modificarle cada una con su media 
df.isnull().sum()

                            FECHA        PRECIP          EVAP          TMAX  \
count                       19574  19534.000000  19302.000000  19569.000000
mean   1989-03-01 18:02:01.385511      2.217452      4.882157     34.468808
min           1961-01-01 00:00:00      0.000000      0.000000     18.000000
25%           1974-05-26 06:00:00      0.000000      3.200000     32.500000
50%           1987-11-18 12:00:00      0.000000      4.500000     35.000000
75%           2004-04-09 18:00:00      0.000000      6.500000     37.000000
max           2018-07-31 00:00:00    217.400000     15.600000     45.500000
std                           NaN      9.015782      2.279340      3.430054

               TIMN
count  19568.000000
mean      16.657420
min       -2.500000
25%       11.000000
50%       16.500000
75%       23.000000
max       29.000000
std        6.248605

FECHA       0
PRECIP     40
EVAP      272
TMAX        5
TIMN        6
dtype: int64

# Despues de conocer y analizar la etapa de diagnostico, ahora sigue hacer la limpieza de datos con las instrucciones dadas en nuestro Proyecto

In [6]:
#Conteo de registros faltantes por fecha
columnas = ["PRECIP", "EVAP", "TMAX", "TIMN"]
df["faltantes"] = df[columnas].isnull().sum(axis=1)
df[df["faltantes"] > 0][["FECHA", "faltantes"]]

#La respuesta indicara cuantos nulos hay faltantes en cada fecha, dando un total de 312 columnas con registros faltantes

           FECHA  faltantes
0     1961-01-01          1
1     1961-01-02          1
2     1961-01-03          1
3     1961-01-04          1
4     1961-01-05          1
...          ...        ...
18928 2016-07-23          1
18930 2016-07-25          1
19210 2017-06-01          1
19327 2017-09-26          1
19513 2018-06-01          1

[312 rows x 2 columns]

In [7]:
# Rellenar nulos con la media de la columna
df["PRECIP"] = df["PRECIP"].fillna(df["PRECIP"].mean())
df["EVAP"] = df["EVAP"].fillna(df['EVAP'].mean(),inplace=True)
df["TMAX"] = df["TMAX"].fillna(df['TMAX'].mean(),inplace=True)
df["TIMN"] = df["TIMN"].fillna(df['TIMN'].mean(),inplace=True)

C:\Users\tocha\AppData\Local\Temp\ipykernel_26104\3581356060.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["EVAP"] = df["EVAP"].fillna(df['EVAP'].mean(),inplace=True)
C:\Users\tocha\AppData\Local\Temp\ipykernel_26104\3581356060.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["TMAX"] = df["TMAX"].fillna(df['TMAX'].mean(),inplace=True)
C:\Users\tocha\AppData\Local\Temp\ipykernel_26104\3581356060.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["TIMN"] = df["TIMN"].fillna(df['TIMN'].mean(),inplace=True)

In [19]:
df.head(36)

        FECHA  PRECIP      EVAP  TMAX  TIMN  faltantes
0  1961-01-01     0.0  4.882157  25.0  13.0          0
1  1961-01-02     0.0  4.882157  27.5  14.0          0
2  1961-01-03     0.0  4.882157  31.0  11.0          0
3  1961-01-04     0.0  4.882157  32.0  13.0          0
4  1961-01-05     0.0  4.882157  29.0  14.0          0
5  1961-01-06     0.0  4.882157  24.0  14.5          0
6  1961-01-07     0.0  4.882157  28.5  10.0          0
7  1961-01-08     0.0  4.882157  32.0  12.0          0
8  1961-01-09     0.0  4.882157  33.5  11.0          0
9  1961-01-10     0.0  4.882157  32.5   9.5          0
10 1961-01-11     0.0  4.882157  30.0   9.0          0
11 1961-01-12     0.0  4.882157  33.0   9.5          0
12 1961-01-13     0.0  4.882157  32.0  10.0          0
13 1961-01-14     0.0  4.882157  31.0  10.0          0
14 1961-01-15     0.0  4.882157  32.0   8.5          0
15 1961-01-16     0.0  4.882157  31.0  11.0          0
16 1961-01-17     0.1  4.882157  28.0  14.5          0
17 1961-01-18     0.4  4.882157  37.0  17.0          0
18 1961-01-19    13.5  4.882157  23.0  19.5          0
19 1961-01-20    24.0  4.882157  23.0  20.0          0
20 1961-01-21     0.1  4.882157  29.5  16.5          0
21 1961-01-22    17.0  4.882157  20.0  18.0          0
22 1961-01-23    42.0  4.882157  19.5  16.5          0
23 1961-01-24     0.0  4.882157  28.0  13.5          0
24 1961-01-25     0.0  4.882157  30.0  13.0          0
25 1961-01-26     0.0  4.882157  30.5  11.5          0
26 1961-01-27     0.0  4.882157  30.0  11.0          0
27 1961-01-28     0.0  4.882157  30.0  11.0          0
28 1961-01-29     0.0  4.882157  30.0  10.0          0
29 1961-01-30     0.0  4.882157  30.5  12.0          0
30 1961-01-31     0.0  4.882157  33.0  12.0          0
31 1961-02-01     0.0  4.882157  30.0  12.0          0
32 1961-02-02     0.0  4.882157  29.0  13.5          0
33 1961-02-03     0.0  4.882157  30.0  11.5          0
34 1961-02-04     0.0  4.882157  28.0  10.0          0
35 1961-02-05     0.0  4.882157  28.0   8.0          0

In [8]:
#Revisamos que no quede nigun nulo en las columnas
NulosTotales = df.isnull().sum()
NulosTotales

FECHA        0
PRECIP       0
EVAP         0
TMAX         0
TIMN         0
faltantes    0
dtype: int64

In [9]:
#Revisamos que no hay duplicados
duplicados = df.duplicated().sum()
duplicados

np.int64(0)

In [25]:
df.describe()

,FECHA,PRECIP,EVAP,TMAX,TIMN,faltantes
count,19574,19574.000000,19574.000000,19574.000000,19574.000000,19574.0
mean,1989-03-01 18:02:01.385511,2.217452,4.882157,34.468808,16.657420,0.0
min,1961-01-01 00:00:00,0.000000,0.000000,18.000000,-2.500000,0.0
25%,1974-05-26 06:00:00,0.000000,3.200000,32.500000,11.000000,0.0
50%,1987-11-18 12:00:00,0.000000,4.600000,35.000000,16.500000,0.0
75%,2004-04-09 18:00:00,0.000000,6.400000,37.000000,23.000000,0.0
max,2018-07-31 00:00:00,217.400000,15.600000,45.500000,29.000000,0.0
std,NaN,9.006565,2.263447,3.429615,6.247648,0.0